### ISSUE TITLE
race error in scrub-package-json if just deleted that file

### ISSUE THREAD

**Issue by trentm** [trentm/node-kthxbai#1]
```
./node_modules/.bin/kthxbai

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/bunyan/node_modules/mv/node_modules/mkdirp/node_modules/minimist/package.json'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/bin/kthxbai:192:34
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/index.js:34:13
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/node_modules/async/lib/async.js:190:13
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/node_modules/async/lib/async.js:94:25
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/node_modules/async/lib/async.js:187:17
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/index.js:34:13
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/node_modules/async/lib/async.js:190:13
    at /root/data/jenkins/workspace/sdcadm/MG/build/sdcadm/node_modules/kthxbai/node_modules/du/node_modules/async/lib/async.js:94:25
```

That whole tree was removed. Currently we're doing "glob.sync", "rimraf.sync", "glob.sync for package.json files to scrub", "scrub each package.json file".

This started breaking with rimraf@2.3.1. I'm guessing there is a race between rimraf.sync of that deep dir and glob.sync for package.json files finding those files. Which is unfortunate. One flail would be to go async here. At least I've seen comments in rimraf commits about sync being less reliable. Not sure if that's by design.

**Comment by trentm** [comment]
c.f.  TOOLS-872
